Vagrant.configure('2') do |config|
    # Disable /vagrant synced folder
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.define :server_1 do |ubuntu|
        ubuntu.vm.box = 'geerlingguy/ubuntu1604'
        ubuntu.vm.network :private_network, ip: '10.40.40.21'
    end

    config.vm.define :server_2 do |ubuntu|
        ubuntu.vm.box = 'geerlingguy/ubuntu1604'
        ubuntu.vm.network :private_network, ip: '10.40.40.22'
    end

    config.vm.define :server_3 do |ubuntu|
        ubuntu.vm.box = 'geerlingguy/ubuntu1604'
        ubuntu.vm.network :private_network, ip: '10.40.40.23'
    end
end
